### ISSUE TITLE
Bug: exception when user doesn't have a picture

### ISSUE THREAD

**Issue by waldekmastykarz** [DanWahlin/DotnetCoreRazor-MicrosoftGraph#1]
If the user working with the app doesn't have a picture, the app throws unhandled exception

![image](https://user-images.githubusercontent.com/11164679/126501967-6d08b1e1-a936-4638-89fa-01023c02fed5.png)

**Comment by DanWahlin** [comment]
Thanks! Fixed this to hide the image if there isn't one.
